
services:
  postgres:
    image: postgres:16-alpine
    container_name: login_seguro_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: login_seguro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - login_seguro_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d login_seguro"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  login_seguro_network:
    driver: bridge
